### ISSUE TITLE
GPGPU implementation by OpenCL, CUDA and similar

### ISSUE THREAD

**Issue by D3vil0p3r** [evilsocket/legba#11]
One of main purposes of legba is to act as a bruteforcer, so the user sets a protocol and the target is tested by the provided credentials.

Let's guess two scenarios:

### Scenario 1

I manage an IT infrastructure on my company and I wish to test the authentication credentials on 100 endpoints by using several legba plugins (protocols). We could have single endpoints exposing different services by different protocols.

Let's assume also this multi-target mode request has been implemented https://github.com/evilsocket/legba/issues/3

### Scenario 2

I need to use a huge user/password wordlist for a single target.

### Proposal

Let's consider the current [benchmark](https://github.com/evilsocket/legba#benchmark) vs Hydra, in order to improve more the speed of this process in both of the scenarios

Could there be a sense to implement the choice to execute computational processing by GPU instead of CPU by OpenCL libraries (or similar) when legba must manage multitarget or when it must parallelize the sent authentication requests?

The only limit I see is on the target side, how many auth requests at time unit is able to manage.

Hashcat has a similar functionality even if for a different purpose.

My 2 cents: https://stackoverflow.com/questions/9205915/opencl-cpu-device-vs-gpu-device

**Comment by evilsocket** [comment]
I think this is out of scope honestly. While it makes a lot of sense for Hashcat, where all computations happen locally on the CPU, for Legba the bottleneck is network I/O, not computations. Meaning that implementing this would not provide any benefit. Hashcat is CPU-bound, Legba is I/O bound.

What makes Legba faster than Hydra is a better handling of network operations, that is where all optimizations must go.
