### ISSUE TITLE
Enhancement request: --http-failure-string

### ISSUE THREAD

**Issue by v1nc** [evilsocket/legba#17]
When I try to bruteforce a HTTP login form, I often dont know any valid login data, so I only now the failure status code and message.
I can try to guess the success status code, but that is not always correct, also the success and failure status code can be the same in some cases.

A `--http-failure-string` flag would be very helpful. I always know the failure string and can be sure that it does not trigger on success. Hydra also supports this.

It would be great if you implement it, I think it should not be much work to do.

**Comment by evilsocket** [comment]
makes total sense, doing it right now

**Comment by v1nc** [comment]
That was really fast, thank you for your awesome work!

**Comment by evilsocket** [comment]
you're welcome! :D thank you for your feedback and idea
