### ISSUE TITLE
Suggestion: SSH Key Based Authentication

### ISSUE THREAD

**Issue by fullspectrumdev** [evilsocket/legba#2]
It would be exceptionally pleasant to have support for SSH key based auth - provide a directory of SSH private keys, and have the tool test them against target.

**Comment by evilsocket** [comment]
can do! :D

**Comment by evilsocket** [comment]
Done, you can now use glob expressions:

```sh
legba ssh \
    --username root \
    --key '@/some/path/*' \
    --ssh-auth-mode key \
    --target localhost:22
```
