### ISSUE TITLE
building from source failing v0.7.1

### ISSUE THREAD

**Issue by edoardottt** [evilsocket/legba#30]
If anyone is facing this issue when building with `cargo install legba`:
```
error: failed to run custom build command for `pavao v0.2.3`
...
  error: could not find system library 'smbclient' required by the 'pavao' crate
...
```

As declared by the [`pavao readme page`](https://github.com/veeso/pavao?tab=readme-ov-file#debian-based-systems-) you need to install some deps:
```console
sudo apt install -y libsmbclient-dev libsmbclient
```

Done this you should be good to go.

@evilsocket you can close the issue as it's not that useful to keep this open, just wrote this to link that if anyone has this problem.

**Comment by evilsocket** [comment]
From [the wiki](https://github.com/evilsocket/legba/wiki/Installation-and-Building):

![Screenshot 2023-12-19 alle 13 25 36](https://github.com/evilsocket/legba/assets/86922/25613f24-1b40-45ad-9eec-29ff5b28db91)
