### ISSUE TITLE
Legba does not provide formatted output in pgsql plugin

### ISSUE THREAD

**Issue by shizzgar** [evilsocket/legba#37]
I started legba with such example:
`legba pgsql -T 10.3.2.61:5432 -U user -P passpass --output-format csv -O report.csv
`
But it gives only this to stdout:

```bash
legba v0.7.1

[INFO ] target: 10.3.2.61:5432
[INFO ] username -> string 'user'
[INFO ] password -> string 'passpass'
    
[INFO ] runtime 1.000179919s
```
And there is no report.csv. 
The same behavior for other formats.
ssh plugin is work properly, but not this one.

UPD:
Checked mysql plugin, works like a charm:
`legba mysql -T 10.3.2.61:3306 -U user -P passpass --output-format csv -O report.csv
`
```bash
legba v0.7.1

[INFO ] target: 10.3.2.61:3306
[INFO ] username -> string 'user'
[INFO ] password -> string 'passpass'
    
[INFO ] [2024-01-21 23:20:17] (mysql) <10.3.2.61:3306> username=user password=passpass
[INFO ] runtime 1.000235692s
```

I'v used this compose for testing purposes:
```yaml
version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: passpass
        POSTGRES_DB: db
        PGPASSWORD: passpass
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: passpass
      MYSQL_USER: user
      MYSQL_PASSWORD: passpass
      MYSQL_DATABASE: db
    ports:
      - "3306:3306" 
```

**Comment by evilsocket** [comment]
@shizzgar in the pgsql execution logs I don't see valid credentials being found. the file is only generated when a valid username+password is found, as it happened with the mysql plugin instead (and that is why it did generate the file).
