### ISSUE TITLE
BadFileDescriptor

### ISSUE THREAD

**Issue by Mag1cByt3s** [evilsocket/legba#38]
I just tried out legba as it seemed to be a promising alternative to CrackMapExec.

However I am experiencing issues with it:

```bash
docker run -it -v '/home/pascal/Pentesting/OffSec/OSCP/Challenges/Medtech':/medtech -v '/usr/share/wordlists/seclists/Passwords/Leaked-Databases':/wordlists evilsocket/legba:latest smb --target 172.16.236.10 --username /medtech/VM1/users.txt --password /wordlists/rockyou.txt
legba v0.8.0

[INFO ] target: 172.16.236.10
[INFO ] username -> wordlist /medtech/VM1/users.txt
[INFO ] password -> wordlist /wordlists/rockyou.txt
    
[INFO ] searching private share for 172.16.236.10:445 ...
thread 'tokio-runtime-worker' panicked at src/plugins/samba/mod.rs:81:44:
called `Result::unwrap()` on an `Err` value: BadFileDescriptor
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried both the native version as well as the docker version. Both are causing issues.

**Comment by evilsocket** [comment]
Hi @Mag1cByt3s, thanks for your report!

I've pushed a fix, but chances are that the samba module won't be able to automatically find a private share, so you'll also have to pass --smb-share explicitly. In case you are able to pull the fix and test it, you'll probably be warned with an error like:

> could not find private share for <target>, provide one with --smb-share

Let me know wether or not this happens and if you can solve with --smb-share. The Samba module is a bit experimental, I'm looking forward to any feedback you'll be able to provide! Thanks
