### ISSUE TITLE
Telnet brute seems not work(Mac)

### ISSUE THREAD

**Issue by ImTopz** [evilsocket/legba#41]
I test legba on Mac(M1) by docker, my command is 

```bash
docker run -it evilsocket/legba telnet --username admin --password ~/wordlist.txt--target ip:23 --telnet-user-prompt "login: "   --telnet-pass-prompt "Password: "  --telnet-prompt ":~$ " --single-match
```
and then , the output on my shell is like bellow:
[
<img width="857" alt="iShot_2024-04-17_00 01 55" src="https://github.com/evilsocket/legba/assets/80200569/3a0a8602-09b1-4858-b2aa-8f3d2da8370a">
](url)
 really wonder what happend, thx

**Comment by ImTopz** [comment]
the device is my own switch, i change the telnet-user-prompt and the password-prompt for matching the prompt, but still not successfully.

**Comment by evilsocket** [comment]
The wordlist you are trying to use does not exist inside the container, therefore it is considered as a string. Please refer to the documentation on how to share files via docker volumes.

https://github.com/evilsocket/legba/wiki/Installation-and-Building#installing-from-docker-hub

Also, the IP you are targeting might not be visible from within docker network, so you'll need to also add --network host :

```
docker run \
  -v $(pwd):/data \ # shared the current directory as /data inside the container
  --network host \ # docker will use the same network of the host
  -it evilsocket/legba:latest \
  ssh --username root --password /data/your-wordlist.txt --target 192.168.1.1
```

**Comment by ImTopz** [comment]
thx, i'll try to move the wordlist into docker container and make the ip right in the container

**Comment by evilsocket** [comment]
you don't need to, just follow the instructions .... files can be shared with containers via volumes, and ips can be made visible to it by --network host

**Comment by ImTopz** [comment]
ok, thx so much
