### ISSUE TITLE
Ease of use is so poor and trying to use a dictionary is very difficult

### ISSUE THREAD

**Issue by 8848sj** [evilsocket/legba#42]
Wasting my time and blasting very slowly , This is the first time I have encountered a tool with such poor usage logic and ease of use.

**Comment by evilsocket** [comment]
There's a wiki with very complete docs and commands you can literally copy/paste and they work, especially the docker ones. https://github.com/evilsocket/legba/wiki

You probably failed to understand how to pass a file from the host computer to the container.
