### ISSUE TITLE
Password Doesnt take value as a file but it only take as a string. I dont know what is wrong with it

### ISSUE THREAD

**Issue by Teptaikorn123** [evilsocket/legba#55]
jujingyi@DESKTOP-4MKT4IH:~/Pentest$ sudo docker run legba sftp --username ptpadm --password pass.txt --target 10.136.107.102
legba v0.9.0

[INFO ] target: 10.136.107.102
[INFO ] username -> string 'ptpadm'
[INFO ] password -> string 'pass.txt'

[INFO ] tasks=12 mem=31.6 MiB targets=1 attempts=1 done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=12 mem=31.9 MiB targets=1 attempts=1 done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=12 mem=32.2 MiB targets=1 attempts=1 done=0 (0.00%) speed=0 reqs/s
[INFO ] runtime 4.006194642s
jujingyi@DESKTOP-4MKT4IH:~/Pentest$ pwd
/home/jujingyi/Pentest
jujingyi@DESKTOP-4MKT4IH:~/Pentest$ sudo docker run legba sftp --username ptpadm --password /home/jujingyi/pass.txt --target 10.136.107.102
legba v0.9.0

[INFO ] target: 10.136.107.102
[INFO ] username -> string 'ptpadm'
[INFO ] password -> string '/home/jujingyi/pass.txt'

[INFO ] tasks=12 mem=31.5 MiB targets=1 attempts=1 done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=12 mem=31.9 MiB targets=1 attempts=1 done=0 (0.00%) speed=0 reqs/s
[INFO ] tasks=12 mem=32.2 MiB targets=1 attempts=1 done=0 (0.00%) speed=0 reqs/s
[INFO ] runtime 4.005528039s
jujingyi@DESKTOP-4MKT4IH:~/Pentest$

**Comment by evilsocket** [comment]
you are not sharing the file via docker volumes as per documentation, so the file doesn't exist in the docker container and it's used as string.
