### ISSUE TITLE
Consider Developing Legba as a Library

### ISSUE THREAD

**Issue by lanjelot** [evilsocket/legba#58]
Hi,

Congratulations on Legba, this looks like an excellent project and a worthy replacement for Patator/Hydra/Medusa/etc.! As the author of Patator, I wanted to share a reflection from my experience that might be helpful as you develop Legba further.

One thing I wish I had done early on with Patator was to design it as a library from the start, rather than exclusively as a command-line tool. While having a robust CLI is great for most use cases, I found that there are often edge cases or scenarios where it would have been super useful to integrate the functionality programmatically into custom scripts or applications.

By structuring Legba as a library, you could:

* Expose reusable APIs for different attack modules, allowing developers to build their own clients or automate edge cases.
* Retain the same CLI functionality for direct usage, making it flexible for different user needs.

I think a password attack library that offers both programmatic flexibility and CLI ease-of-use would fill a significant gap in the tooling space.

I would love to re-write Patator as a library but i'm afraid i've moved on and lack time and motivation, at least for now :)

Looking forward to seeing how Legba evolves!

Cheers :)

**Comment by evilsocket** [comment]
Hi @lanjelot and thank you!

I've had the same thinking for a while, but then I settled on the fact that if there's a use case that the CLI doesn't cover, I'd rather improve the CLI experience to support it. I also implemented a REST API here https://github.com/evilsocket/legba/blob/main/src/api/mod.rs which essentially makes it into a library / service already.

Do you have any specific use case in mind that woulnd't be possible with the current capabilities?

**Comment by evilsocket** [comment]
Released v0.10.0 with the REST API and [documented it](https://github.com/evilsocket/legba/wiki/REST-API). IMO this approach is way better than a library as it exposes Legba's functionalities to any language. I'll close this issue but please let me know if there are use cases that won't work with this approach and I'll try to extend it!

Thanks again for your feedback
