### ISSUE TITLE
Adding docker-compose.yml

### ISSUE THREAD

**Issue by D3vil0p3r** [evilsocket/legba#9]
Is there the chance (and a sense) to create a `docker-compose.yml` file to deploy the solution by `docker-compose`?

I hope so. Thanks.

**Comment by EsamLasheen** [comment]
Totally on board with this idea! It would be really helpful. Evilsocket, could you please go ahead and create the file? Thanks a bunch.

**Comment by evilsocket** [comment]
Mmm usually docker-compose is used when you have multiple containers that need to interact with each other (for instance a web app with a database), but in this case there's just one container that you can already execute via docker ... a docker-compose.yml would simply reference the same container that you would use with docker ... am I missing something? What would be the usefulness?

**Comment by D3vil0p3r** [comment]
Thank you for the answer. I was thinking several useful elements for a single-container scenario:
* allow to have container running consistently (with standard configuration) across different environments (i.e., development, testing, production)
* useful for portability, since Docker Compose files can be versioned and shared with others, making it easy to share and collaborate on single-container setups.
* [preserving volume data](https://docs.docker.com/compose/features-uses/#preserves-volume-data-when-containers-are-created)
* [configuration caching](https://docs.docker.com/compose/features-uses/#only-recreate-containers-that-have-changed)

Apart these elements above, probably it could be useful for any future expansion of the project in case additional containers will be added in the future that allows you to scale the application more easily when needed.

By the way, I would add legba to [Athena Cyber Hub](https://github.com/Athena-OS/athena-cyber-hub)

**Comment by evilsocket** [comment]
You do have some valid points there! :D Will do, it'll be pretty easy anyway

**Comment by evilsocket** [comment]
@D3vil0p3r check the [docker-compose.yml](https://github.com/evilsocket/legba/blob/main/docker-compose.yml) out! Instead of using an actual volume I thought that just sharing ./ would be easier. That's how most people would use the docker image anyway ... what do you think? Other useful additions you can think about?

**Comment by D3vil0p3r** [comment]
Thank you very much! Currently I don't have further additions to propose but when I start to use legba massively, I can come back to the compose file in case I get some new proposal in my mind ^^

**Comment by evilsocket** [comment]
looking forward to it

**Comment by niqdev** [comment]
@D3vil0p3r FYI check the description in this issue for an example https://github.com/evilsocket/legba/issues/24

it's basically creating a container under the hood, mounting a shared volume `/hck/share` between boxes and tasks (both on docker and on kubernetes) and it allows to connect to a vpn seamlessly, which i guess is what you are trying to achieve with a docker-compose
